### ISSUE TITLE
Inbox Page

### ISSUE THREAD

**Issue by gargmegham** [Servcy/Client#9]

**Comment by karnagarg** [comment]
how far along are we on this @gargmegham?

**Comment by karnagarg** [comment]
Please create some designs for inbox module this week @karnagarg

**Comment by karnagarg** [comment]
@gargmegham I'll take a look at this tomorrow. I'll give you an update when i complete this one.

**Comment by karnagarg** [comment]
@gargmegham I'll take a look at this tomorrow. I'll give you an update when i complete this one.

**Comment by karnagarg** [comment]
@gargmegham I'll take a look at this tomorrow. I'll give you an update when i complete this one.

**Comment by karnagarg** [comment]
vdswv

**Comment by karnagarg** [comment]
few

**Comment by karnagarg** [comment]
few

**Comment by karnagarg** [comment]
fdg

**Comment by karnagarg** [comment]
@gargmegham I'll take a look at this tomorrow. I'll give you an update when i complete this one.

**Comment by karnagarg** [comment]
@gargmegham I'll take a look at this tomorrow. I'll give you an update when i complete this one.

**Comment by gargmegham** [comment]
For my own reference: Slack & Github events display is pending
